<?php
$createUrl = $this->url('tiny-crm/default', [
    'controller' => 'databases', 
    'action' => 'create'
]);
$flashMessenger = $this->flashMessenger()->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>')->setMessageCloseString('</div>');
?>
<section class="content-header">
    <?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
    <h1><?php echo $pageTitle; ?></h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <a class="btn btn-app" href="<?php echo $createUrl; ?>"><i class="fa fa-plus"></i>New</a>
        <div class="col-xs-12">
    </div>
    <div class="row">
        <div class="col-xs-8">
            <?php echo $this->partial('tiny-crm/databases/partials/table-databases'); ?>
        </div>
        <div class="col-xs-4">
            <?php echo $this->partial('tiny-crm/databases/partials/table-upload-contacts-statuses'); ?>
        </div>
    </div>
</section>