<?php
$getContactsUrl = $this->url('tiny-crm/default', [
    'controller' => 'databases', 
    'action' => 'get-contacts'
]);
$flashMessenger = $this->flashMessenger()->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>')->setMessageCloseString('</div>');
?>
<section class="content-header">
    <?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
    <h1><?php echo $pageTitle; ?></h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <a class="btn btn-app" href="<?php echo $getContactsUrl; ?>"><i class="fa fa-download"></i>Get contacts</a>
        <div class="col-xs-12">
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div style="cursor: move;" class="nav-tabs-custom">
                <!-- Tabs within a box -->
                <ul class="nav nav-tabs pull-right ui-sortable-handle">

                    <li class="active"><a href="#inprogress" data-toggle="tab">In progress</a></li>
                    <li><a href="#toll1" data-toggle="tab">Toll1</a></li>
                    <li><a href="#toll2" data-toggle="tab">Toll2</a></li>
                    <li><a href="#toll3" data-toggle="tab">Toll3</a></li>
                    <li><a href="#closed" data-toggle="tab">Closed</a></li>

                    <li class="pull-left header"><i class="fa fa-inbox"></i> Contacts</li>
                </ul>
                <div class="tab-content no-padding">
                      <!-- Morris chart - Sales -->
                    <div id="inprogress" class="chart tab-pane active">
                        <?php echo $this->partial('tiny-crm/databases/partials/table-contacts-inprogress'); ?>
                    </div>
                    <div id="closed" class="chart tab-pane">
                        <?php echo $this->partial('tiny-crm/databases/partials/table-contacts-closed'); ?>
                    </div>
                    <div id="toll1" class="chart tab-pane">
                        <?php echo $this->partial('tiny-crm/databases/partials/table-contacts-toll1'); ?>
                    </div>
                    <div id="toll2" class="chart tab-pane">
                        <?php echo $this->partial('tiny-crm/databases/partials/table-contacts-toll2'); ?>
                    </div>
                    <div id="toll3" class="chart tab-pane">
                        <?php echo $this->partial('tiny-crm/databases/partials/table-contacts-toll3'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>