<?php
$uploadCsvUrl = $this->url('tiny-crm/default', [
    'controller' => 'databases', 
    'action' => 'upload-csv',
    'entityId' => $database->getId(),
]);
$downloadCsvUrl = $this->url('tiny-crm/default', [
    'controller' => 'databases',
    'action' => 'download-csv',
    'entityId' => $database->getId(),
]);
$flashMessenger = $this->flashMessenger()->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>')->setMessageCloseString('</div>');
?>
<section class="content-header">
    <?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
    <h1><?php echo $pageTitle; ?></h1>
    <!-- <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Layout</a></li>
        <li class="active">Fixed</li>
    </ol> -->
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <a class="btn btn-app" href="<?php echo $uploadCsvUrl; ?>"><i class="fa fa-upload"></i>Upload .csv</a>
            <!-- <a class="btn btn-app" href="<?php //echo $downloadCsvUrl; ?>"><i class="fa fa-plus"></i>Enter</a> -->
            <!-- <a class="btn btn-app" href="<?php //echo $createUrl; ?>"><i class="fa fa-refresh fa-spin"></i>Refresh</a> -->
            <!-- <a class="btn btn-app" href="<?php echo $downloadCsvUrl; ?>"><i class="fa fa-download"></i>Download</a> -->
        <div class="col-xs-12">
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Contacts</h3>
                    <!-- <div class="box-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input name="table_search" class="form-control pull-right" placeholder="Search" type="text">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </div> -->
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                <?php //var_dump($contacts); die('fff'); ?>
                    <?php echo $this->partial('tiny-crm/databases/partials/table-contacts-administrator', [
                        'contacts' => $contacts,
                        'editCommentForm' => $editCommentForm,
                        'moveScheduleForm' => $moveScheduleForm,
                        'closedForm' => $closedForm]); 
                    ?>
                </div>
                <!-- /.box-body -->
            </div>
          <!-- /.box -->
        </div>
      </div>
</section>