<?php
$uploadCsvUrl = $this->url('tiny-crm/default', [
    'controller' => 'databases', 
    'action' => 'upload-csv',
    'entityId' => $database->getId(),
]);
$downloadCsvUrl = $this->url('tiny-crm/default', [
    'controller' => 'databases',
    'action' => 'download-csv',
    'entityId' => $database->getId(),
]);
$flashMessenger = $this->flashMessenger()->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>')->setMessageCloseString('</div>');
?>
<section class="content-header">
    <?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
    <h1><?php echo $pageTitle; ?></h1>
    <!-- <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Layout</a></li>
        <li class="active">Fixed</li>
    </ol> -->
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <a class="btn btn-app" href="<?php echo $uploadCsvUrl; ?>"><i class="fa fa-upload"></i>Upload CSV</a>
            <!-- <a class="btn btn-app" href="<?php echo $uploadCsvUrl; ?>"><i class="fa fa-upload"></i>Uploads log</a> -->
            <!-- <a class="btn btn-app" href="<?php //echo $downloadCsvUrl; ?>"><i class="fa fa-plus"></i>Enter</a> -->
            <!-- <a class="btn btn-app" href="<?php //echo $createUrl; ?>"><i class="fa fa-refresh fa-spin"></i>Refresh</a> -->
            <!-- <a class="btn btn-app" href="<?php echo $downloadCsvUrl; ?>"><i class="fa fa-download"></i>Download</a> -->
        <div class="col-xs-12">
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Contacts</h3>
                    <!-- <div class="box-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input name="table_search" class="form-control pull-right" placeholder="Search" type="text">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </div> -->
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="progress-group">
                                <span class="progress-text">Contacts Pending + Lead</span>
                                <span class="progress-number"><b><?php echo $contacts['Pending'] + $contacts['Lead']; ?></b>/<?php echo $contacts['Total']; ?></span>
                                <?php 
                                $pendingPerc = ($contacts['Pending'] + $contacts['Lead']) / $contacts['Total'] * 100;
                                ?>
                                <div class="progress sm">
                                    <div class="progress-bar progress-bar-aqua" style="<?php echo 'width:' . $pendingPerc . '%' ?>"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="row">
                        <div class="col-sm-3 col-xs-6">
                            <div class="description-block border-right">
                                <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 17%</span>
                                <h5 class="description-header"><?php echo $contacts['Closed']; ?></h5>
                                <span class="description-text">CLOSED</span>
                            </div>
                            <!-- /.description-block -->
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                            <div class="description-block border-right">
                                <span class="description-percentage text-yellow"><i class="fa fa-caret-left"></i> 0%</span>
                                <h5 class="description-header"><?php echo $contacts['Toll1']; ?></h5>
                                <span class="description-text">TOLL 1</span>
                            </div>
                            <!-- /.description-block -->
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                            <div class="description-block border-right">
                                <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 20%</span>
                                <h5 class="description-header"><?php echo $contacts['Toll2']; ?></h5>
                                <span class="description-text">TOLL 2</span>
                            </div>
                            <!-- /.description-block -->
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                            <div class="description-block">
                                <span class="description-percentage text-red"><i class="fa fa-caret-down"></i> 18%</span>
                                <h5 class="description-header"><?php echo $contacts['Toll3']; ?></h5>
                                <span class="description-text">TOLL 3</span>
                            </div>
                            <!-- /.description-block -->
                        </div>
                    </div>
                    <!-- /.row -->
                </div>
            </div>
          <!-- /.box -->
        </div>
      </div>
</section>