<?php
$uploadCsvUrl = $this->url('tiny-crm/default', [
    'controller' => 'databases', 
    'action' => 'upload-csv',
    'entityId' => $database->getId(),
]);
$downloadCsvUrl = $this->url('tiny-crm/default', [
    'controller' => 'databases',
    'action' => 'download-csv',
    'entityId' => $database->getId(),
]);
$flashMessenger = $this->flashMessenger()->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>')->setMessageCloseString('</div>');
?>
<section class="content-header">
    <?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
    <h1><?php echo $pageTitle; ?></h1>
    <!-- <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Layout</a></li>
        <li class="active">Fixed</li>
    </ol> -->
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <a class="btn btn-app" href="<?php echo $uploadCsvUrl; ?>"><i class="fa fa-upload"></i>Upload .csv</a>
            <!-- <a class="btn btn-app" href="<?php //echo $downloadCsvUrl; ?>"><i class="fa fa-plus"></i>Enter</a> -->
            <!-- <a class="btn btn-app" href="<?php //echo $createUrl; ?>"><i class="fa fa-refresh fa-spin"></i>Refresh</a> -->
            <a class="btn btn-app" href="<?php echo $downloadCsvUrl; ?>"><i class="fa fa-download"></i>Download</a>
        <div class="col-xs-12">
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Contacts</h3>
                    <div class="box-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input name="table_search" class="form-control pull-right" placeholder="Search" type="text">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tbody><tr>
                            <th>ID</th>
                            <th>User</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Action</th>
                        </tr>
                        <?php 
                        foreach ($contacts as $contact): 
                            $viewUrl = $this->url('tiny-crm/default', [
                                'controller' => 'contacts', 
                                'action' => 'view',
                                'entityId' => $database->getId(),
                            ]);
                        ?>
                        <tr>
                            <td><?php echo $contact['id']; ?></td>
                            <td><a href="<?php //echo $viewUrl; ?>"?><?php echo $contact['fullName']; ?></td>
                            <td><?php echo $contact['phone']; ?></td>
                            <td><?php echo $contact['email']; ?></td>
                            <td></td>
                        </tr>
                        <?php endforeach ?>
                    </tbody></table>
                </div>
                <!-- /.box-body -->
            </div>
          <!-- /.box -->
        </div>
      </div>
</section>