<section class="content-header">
	<h1><?php echo $pageTitle; ?></h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li><a href="#">Layout</a></li>
		<li class="active">Fixed</li>
	</ol>
</section>
<section class="content">
<div class="row">
    <div class="col-xs-9">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Responsive hover table</h3>

          <div class="box-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
              <input name="table_search" class="form-control pull-right" placeholder="Search" type="text">

              <div class="input-group-btn">
                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
                <tbody><tr>
                    <th>ID</th>
                    <th>User</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Reason</th>
                </tr>
                <?php foreach ($schedule as $time => $contacts): ?>
                <?php if(empty($contacts)): ?>
                <tr>
                    <td><?php echo $time; ?></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <?php else: ?>
                <?php 
                foreach ($contacts as $contact): 
                    $editContactUrl = $this->url('tiny-crm/default', [
                        'controller' => 'contacts', 
                        'action' => 'edit',
                        'entityId' => $contact->getId(),
                    ]);
                ?>
                 <tr>
                    <td><?php echo $time; ?></td>
                    <td><a href="<?php echo $editContactUrl; ?>"?><?php echo $contact->getFullName(); ?></a></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>       
                <?php endforeach; ?>
                <?php endif; ?>
                
                <?php endforeach; ?>
            </tbody></table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <div class="col-xs-3 text-center">
        <div id="date-select"></div>
    <!-- <input id="date-select"></input> -->
    </div>
  </div>
</section>

<script type="text/javascript">
// jQuery('#date-select').datetimepicker({
//     format:'d.m.Y H:i',
//     inline:true,
//     lang:'ru',
//     timepicker:false,
//     onSelectDate:function(ct, $i) {
//         console.log('fff');
//         console.log(ct.getDate());
//         console.log(ct.getMonth());
//         console.log(ct.getFullYear());
//         console.log(ct.toString());
//         console.log(moment(ct).format('l'));
//         var encoded = encodeURIComponent(moment(ct).format('l'));
//         var decoded = decodeURIComponent(encoded);
//         console.log(encoded);
//         console.log(decoded);
//         window.location.href = "/?date=" + encoded;
//     },
//     onGenerate: function(current_time, $input) {
//         console.log(current_time);
//         console.log($input);
//     }
// });
</script>

<script type="text/javascript">
    // var disabledDays = ["2016-3-19", "2016-3-3"];
    var disabledDays = <?php echo json_encode($calendar['dates']); ?>;
    var tips = ['some description1', 'some other description2'];
    // var hrefs = ['http://www.bbc.com/', 'http://www.cnn.com/'];
    var hrefs = <?php echo json_encode($calendar['queries']); ?>;

    $("#date-select").datepicker({
        navigationAsDateFormat: true, 
        nextText: '', 
        prevText: '',
        showButtonPanel: false,
        firstDay: 1,
        dateFormat: 'yyyy-mm-dd',
        beforeShowDay: function (date) {
            // console.log(date);
            var m = date.getMonth(),
                d = date.getDate(),
                y = date.getFullYear();
            for (var i = 0; i < disabledDays.length; i++) {
                if ($.inArray(y + '-' + (m + 1) + '-' + d, disabledDays) != -1) {
                    return [true, 'highlight', tips[disabledDays.indexOf(y + '-' + (m + 1) + '-' + d)]];
                }
            }
            return [true];
        },
        onSelect: function(dateText, inst) {        
            var date = new Date(dateText.slice(4)),
                m = date.getMonth(),
                d = date.getDate(),
                y = date.getFullYear();        
            if ($.inArray(y + '-' + (m + 1) + '-' + d, disabledDays) != -1) {
                window.location = hrefs[disabledDays.indexOf((y + '-' + (m + 1) + '-' + d))];
            }
        }
    });
</script>