<?php $form->prepare(); ?>
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title"><?php echo $form->getTitle(); ?></h3>
    </div>
    <!-- form start -->
    <?php echo $this->form()->openTag($form); ?>
    <div class="box-body">
        <div class="form-group">
            <?php echo $this->formLabel($this->form->get('name')); ?>
            <div class="col-sm-10">
                <?php echo $this->formInput($this->form->get('name')); ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Individual</label>
            <div class="col-sm-10">
                <div class="checkbox">
                    <label> 
                        <?php echo $this->formCheckbox($this->form->get('individual')); ?>
                        <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('individual')); ?>
                    <label> 
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Visible for</label>
            <div class="col-sm-10">
                <div class="checkbox">    
                    <?php echo $this->formMultiCheckbox($this->form->get('managers')); ?>
                    <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('managers')); ?>
                </div>
            </div>
        </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <?php echo $this->formSubmit($this->form->get('submit')); ?>
    </div>
    <!-- /.box-footer -->
    <?php echo $this->form()->closeTag($form); ?>
</div>