<?php $form->prepare(); ?>
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title"><?php echo $form->getTitle(); ?></h3>
    </div>
    <!-- form start -->
    <?php echo $this->form()->openTag($form); ?>
    <div class="box-body">
        <div class="form-group">
            <?php echo $this->formLabel($this->form->get('search')); ?>
            <div class="col-sm-10">
                <?php echo $this->formInput($this->form->get('search')); ?>
                <?php //echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('image')); ?>
            </div>
        </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <?php echo $this->formSubmit($this->form->get('submit')); ?>
    </div>
    <!-- /.box-footer -->
    <?php echo $this->form()->closeTag($form); ?>
</div>