<div class="box">
    <div class="box-header">
        <h3 class="box-title">Log of uploads</h3>
        <!-- <div class="box-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
                <input name="table_search" class="form-control pull-right" placeholder="Search" type="text">
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </div>
            </div>
        </div> -->
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <?php if (empty($statuses)): ?>
            No logs yet.
        <?php else: ?>
        <table class="table table-hover table-upload-contacts-statuses" id="statuses-table">
            <thead>
                <tr>
                    <!-- <th>Time</th> -->
                    <th>Database</th>
                    <th>Status</th>
                    <th>Report</th>
                </tr>
            </thead>
            <tbody>
                <?php 
                foreach ($statuses as $status): 
                    $downloadReportUrl = $this->url('tiny-crm/default', [
                        'controller' => 'databases',
                        'action' => 'download-contacts-enter-report',
                        'entityId' => $status->getId(),
                    ]);

                    $databases = $status->getDatabases();
                ?>
                <tr id="status-id-<?php echo $status->getId(); ?>" class="table-item">
                    <!-- <td><?php  ?></td> -->
                    <td>
                    <?php 
                    foreach ($databases as $database) {
                        $viewDatabaseUrl = $this->url('tiny-crm/default', [
                            'controller' => 'databases',
                            'action' => 'view',
                            'entityId' => $database->getId(),
                        ]);
                        echo '<a href="' . $viewDatabaseUrl . '">' . $database->getName() . '</a>' . '<br>';
                        echo is_null($status->getFinishedAt()) ? 'In progress' : $status->getFinishedAt()->format('d M @ H:i');
                    }
                    ?>
                    </td>
                    <td>
                        <div class="text-yellow">Total: <strong><?php echo $status->getNumTotalContacts(); ?></strong></div>
                        <div class="text-green">Added: <strong><?php echo $status->getNumContactsAdded(); ?></strong></div>
                        <div class="text-red">Exists: <strong><?php echo $status->getNumContactsExist(); ?></strong></div>
                        <!-- <dl class="dl-horizontal">
                            <dt>Total contacts:</dt>
                            <dd><?php echo $status->getNumTotalContacts(); ?></dd>
                            <dt>Added:</dt>
                            <dd><?php echo $status->getNumContactsAdded(); ?></dd>
                            <dt>Already exists:</dt>
                            <dd><?php echo $status->getNumContactsExist(); ?></dd>
                        </dl> -->
                    </td>
                    <td><a href="<?php echo $downloadReportUrl; ?>">Download</a></td>
                </tr>
                <?php endforeach ?>
        </tbody></table>
        <?php endif; ?>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->
<script type="text/javascript">
jQuery(document).ready(function() {
    // TinyCRM.initDatabasesInit();
});
</script>