<table class="table table-hover">
    <tbody>
        <tr>
            <th class="col-md-1">ID</th>
            <th class="col-md-3">Contact</th>
            <th class="col-md-3">Info</th>
            <th class="col-md-5">Comment</th>
        </tr>
        <?php 
        foreach ($contacts as $contact): 
            $contactId = is_array($contact) ? $contact['id'] : $contact->getId();
            $contactFullName = is_array($contact) ? $contact['fullName'] : $contact->getFullName();
            $contactPhone = is_array($contact) ? $contact['phone'] : $contact->getPhone();
            $contactEmail = is_array($contact) ? $contact['email'] : $contact->getEmail();
            $contactComment = is_array($contact) ? $contact['comment'] : $contact->getComment();

            $editContactUrl = $this->url('tiny-crm/default', [
                'controller' => 'contacts', 
                'action' => 'edit',
                'entityId' => $contactId,
            ]);
        ?>
        <tr>
            <td><?php echo $contactId; ?></td>
            <td><a href="<?php echo $editContactUrl; ?>"?><?php echo $contactFullName; ?></td>
            <td>
                <?php echo $contactPhone; ?><br>
                <small><?php echo $contactEmail; ?></small>
            </td>
            <td><?php echo $contactComment; ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>