<?php 
$createDatabaseUrl = $this->url('tiny-crm/default', [
    'controller' => 'databases', 
    'action' => 'create'
]);
$searchForm->prepare();
$searchForm->get('search')->setAttribute('class', 'form-control pull-right');
?>
<div class="box">
    <div class="box-header">
        <h3 class="box-title">Database</h3>
        <div class="box-tools">
            <?php echo $this->form()->openTag($searchForm); ?>
            <div class="input-group input-group-sm" style="width: 300px;">
                <!-- <input name="table_search" class="form-control pull-right" placeholder="Search" type="text"> -->
                <?php echo $this->formInput($this->searchForm->get('search')); ?>
                <div class="input-group-btn">
                    <!-- <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button> -->
                    <?php echo $this->formInput($this->searchForm->get('submit')); ?>
                </div>
            </div>
            <?php echo $this->form()->closeTag($searchForm); ?>
        </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <?php if (empty($entities)): ?>
            No databases yet. <a href="<?php echo $createDatabaseUrl; ?>">Create</a> one first.
        <?php else: ?>
        <table class="table table-hover" id="contacts-table">
            <thead><tr>
                <th>Database</th>
                <th class="text-center">Contacts</th>
                <th>Export</th>
                <th class="text-center">Permissions</th>
                <th class="text-center">Actions</th>
            </tr></thead>
            <tbody>
            <?php 
            foreach ($entities as $database): 
            	$viewUrl = $this->url('tiny-crm/default', [
				    'controller' => 'databases',
				    'action' => 'view',
				    'entityId' => $database['entity']->getId(),
				]);
                $updateExportUrl = $this->url('tiny-crm/default', [
                    'controller' => 'databases',
                    'action' => 'update-export-csv',
                    'entityId' => $database['entity']->getId(),
                ]);
                $updateStateExportUrl = $this->url('tiny-crm/default', [
                    'controller' => 'databases',
                    'action' => 'update-state-export',
                    'entityId' => $database['entity']->getId(),
                ]);
                $downloadCsvUrl = $this->url('tiny-crm/default', [
                    'controller' => 'databases',
                    'action' => 'download-csv',
                    'entityId' => $database['entity']->getId(),
                ]);
                $uploadCsvUrl = $this->url('tiny-crm/default', [
                    'controller' => 'databases', 
                    'action' => 'upload-csv',
                    'entityId' => $database['entity']->getId(),
                ]);
            ?>
            <tr id="<?php echo $database['entity']->getId(); ?>" class="table-item">
                <td>
                    <a href="<?php echo $viewUrl; ?>"?><?php echo $database['entity']->getName(); ?></a><br>
                    <?php echo $database['count']; ?>
                </td>
                <td>
                    <?php if($database['count'] != 0): ?>
                    <div class="progress-group">
                        <span class="progress-text">Leads + Pending</span>
                        <span class="progress-number"><b><?php echo $database['pending'] + $database['leads']; ?></b>/<?php echo $database['count']?></span>
                        <div class="progress xxs">
                            <?php $pendingPerc = ($database['pending'] + $database['leads']) / $database['count'] * 100; ?>
                            <div class="progress-bar progress-bar-aqua" style="<?php echo 'width:' . $pendingPerc . '%' ?>"></div>
                        </div>
                    </div>
                    <?php endif; ?>
                </td>
                <td id="export-database-<?php echo $database['entity']->getId(); ?>" data-update-state-export-url="<?php echo $updateStateExportUrl; ?>" data-download-csv-url="<?php echo $downloadCsvUrl; ?>" data-update-export-url="<?php echo $updateExportUrl; ?>">
                    <?php if($database['count'] == 0): ?>
                        No contacts uploaded. <a href="<?php echo $uploadCsvUrl; ?>">Upload</a> CSV file.
                    <?php elseif(!empty($database['export-status'])): ?>
                    <a href="<?php echo $downloadCsvUrl; ?>">Download</a><br>
                    <small>
                        <?php echo "From: " . $database['export-status']->getFinishedAt()->format('d/m/Y H:i'); ?>
                        <a href="javascript:updateExport('<?php echo $database['entity']->getId(); ?>')"><i class="fa fa-refresh"></i></a>
                    </small>
                    <?php else: ?>
                        <a href="javascript:updateExport('<?php echo $database['entity']->getId(); ?>')"><i class="fa fa-refresh"></i></a>
                    <?php endif; ?>
                </td>
                <td class="text-center">
                    <?php 
                    if($database['entity']->getIndividual()):
                        foreach ($database['entity']->getManagers() as $key => $manager): 
                            $editManagerUrl = $this->url('tiny-crm/default', [
                                'controller' => 'managers',
                                'action' => 'edit',
                                'entityId' => $manager->getId(),
                            ]);
                    ?>
                        <a href="<?php echo $editManagerUrl; ?>"?><?php echo $manager->getFullName(); ?></a><br>
                    <?php endforeach; ?>
                    <?php else: ?>
                    All
                    <?php endif; ?>
                </td>
                <td class="text-center" style="vertical-align: middle;">
                    <?php echo $this->partial('tiny-crm/databases/partials/action-button-databases', [
                        'database' => $database['entity'],
                        // 'editCommentForm' => $editCommentForm,
                        // 'moveScheduleForm' => $moveScheduleForm,
                        // 'closedForm' => $closedForm
                    ]); ?>
                </td>
            </tr>
            <?php endforeach ?>
        </tbody></table>
        <?php endif; ?>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->
<script type="text/javascript">
jQuery(document).ready(function() {
    TinyCRM.initDatabasesTable();
});
</script>