<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ; ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            // Custom css for datepicker http://www.hongkiat.com/blog/jquery-ui-datepicker/
            ->prependStylesheet($this->basePath('/assets/css/datepicker.css'))
            // Admin LTE
            ->prependStylesheet($this->basePath('/assets/plugins/admin-lte/dist/css/skins/_all-skins.min.css'))
            ->prependStylesheet($this->basePath('/assets/plugins/admin-lte/dist/css/AdminLTE.css'))
            // Datepicker jquery plugin 
            ->prependStylesheet($this->basePath('/assets/plugins/datetimepicker/jquery.datetimepicker.css'))
            // Font Awesome
            ->prependStylesheet($this->basePath('/assets/plugins/fontawesome/css/font-awesome.min.css'))
            // Bootstrap
            // ->prependStylesheet($this->basePath('/assets/plugins/bootstrap/dist/css/bootstrap-theme.css'))
            ->prependStylesheet($this->basePath('/assets/plugins/bootstrap/dist/css/bootstrap.css'))
        ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('/assets/js/tiny-crm.js'))
            // JQuery UI
            ->prependFile($this->basePath('/assets/plugins/jquery-ui/jquery-ui.min.js'))
            // Moment 
            ->prependFile($this->basePath('/assets/plugins/moment/min/moment.min.js'))
            // Datepicker jquery plugin 
            ->prependFile($this->basePath('/assets/plugins/datetimepicker/build/jquery.datetimepicker.full.min.js'))
            // Admin LTE
            ->prependFile($this->basePath('/assets/plugins/admin-lte/dist/js/demo.js'))
            ->prependFile($this->basePath('/assets/plugins/admin-lte/dist/js/app.min.js'))
            ->prependFile($this->basePath('/assets/plugins/admin-lte/plugins/fastclick/fastclick.js'))
            // Bootstrap
            ->prependFile($this->basePath('/assets/plugins/bootstrap/dist/js/bootstrap.min.js'))
            ->prependFile($this->basePath('/assets/plugins/jquery/dist/jquery.js'))
            // ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            // ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="hold-transition skin-blue sidebar-collapse sidebar-mini layout-boxed">
        <div class="wrapper">
            <?php echo $this->partial('layout/partials/header'); ?>
            <?php echo $this->partial('layout/partials/main-sidebar'); ?>
            <div class="content-wrapper">
                <?php echo $this->content; ?>
            </div>
            <?php echo $this->partial('layout/partials/footer'); ?>
            <?php //echo $this->partial('layout/partials/control-sidebar'); ?>
        </div>
        <?php echo $this->inlineScript() ?>
        <script>
            var AdminLTEOptions = {
                //Enable sidebar expand on hover effect for sidebar mini
                //This option is forced to true if both the fixed layout and sidebar mini
                //are used together
                // sidebarExpandOnHover: true,
                //BoxRefresh Plugin
                // enableBoxRefresh: true,
                //Bootstrap.js tooltip
                // enableBSToppltip: true
            };
        </script>
    </body>
</html>
