<?php 
$navigation = $this->navigation('TinyCrmNavigation')
    ->menu()
    ->setUlClass('sidebar-menu')
    ->setAddClassToListItem(true)
    ->escapeLabels(false);
    //->setPartial('trade/partials/navigation');//->setMaxDepth(0);
?>
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p><?php echo empty($this->identity()) ? 'Unknown' : $this->identity()->getFullName(); ?></p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <!-- <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form> -->
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
        <li class="header">GENERAL</li>
    </ul>
    <?php echo $navigation; ?>
     
    </section>
    <!-- /.sidebar -->
  </aside>