<section class="content-header">
    <h1><?php echo $pageTitle; ?></h1>
    <!-- <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Layout</a></li>
        <li class="active">Fixed</li>
    </ol> -->
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
        	<?php echo $this->partial('tiny-crm/managers/partials/form'); ?>
        </div>
    </div>
</section>
