<?php
$createUrl = $this->url('tiny-crm/default', [
    'controller' => 'managers', 
    'action' => 'create'
]);
$flashMessenger = $this->flashMessenger()->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>')->setMessageCloseString('</div>'); 
// echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
    <h1><?php echo $pageTitle; ?></h1>
    <!-- <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Layout</a></li>
        <li class="active">Fixed</li>
    </ol> -->
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <a class="btn btn-app" href="<?php echo $createUrl; ?>"><i class="fa fa-user-plus"></i>New</a>
        <div class="col-xs-12">
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Managers</h3>
                    <div class="box-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input name="table_search" class="form-control pull-right" placeholder="Search" type="text">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tbody><tr>
                            <th>ID</th>
                            <th>User</th>
                            <th>Date</th>
                            <th>Status</th>
                            <th>Reason</th>
                        </tr>
                        <?php 
                        foreach ($entities as $user): 
                            $editUrl = $this->url('tiny-crm/default', [
                                'controller' => 'managers', 
                                'action' => 'edit',
                                'entityId' => $user->getId(),
                            ]);
                            $role = $user->getRole()->getName();
                            switch ($role) {
                                case 'administrator':
                                    $role = '<span class="label label-success">Administrator</span>';
                                    break;
                                case 'manager':
                                    $role = '<span class="label label-primary">Manager</span>';
                                    break;
                                default:
                                    # code...
                                    break;
                            }
                        ?>
                        <tr>
                            <td><?php echo $user->getId(); ?></td>
                            <td><a href="<?php echo $editUrl; ?>"><?php echo $user->getFullName(); ?></a></td>
                            <td><?php echo $role; ?></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <?php endforeach ?>
                    </tbody></table>
                </div>
                <!-- /.box-body -->
            </div>
          <!-- /.box -->
        </div>
      </div>
</section>