<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Tiny</b>CRM</a>
    <!-- <img src="/assets/img/kk_logo.png" style="max-height:50px;padding-left:20px"> -->
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>

    <!-- <form action="../../index2.html" method="post"> -->
    <?php echo $this->form()->openTag($form); ?>
      <div class="form-group has-feedback">
        <!-- <input class="form-control" placeholder="Email" type="email"> -->
        <?php echo $this->formInput($this->form->get('email')); ?>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <!-- <input class="form-control" placeholder="Password" type="password"> -->
        <?php echo $this->formInput($this->form->get('password')); ?>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <!-- <b>Tiny</b>CRM</a> -->
          <!-- <img src="/assets/img/kk_logo.jpeg" style="max-height:40px;padding-left:20px"> -->
          <!-- <div class="checkbox icheck">
            <label>
              <div aria-disabled="false" aria-checked="false" style="position: relative;" class="icheckbox_square-blue"><input style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;" type="checkbox"><ins style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;" class="iCheck-helper"></ins></div> Remember Me
            </label>
          </div> -->
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <!-- <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button> -->
          <?php echo $this->formSubmit($this->form->get('submit')); ?>
        </div>
        <!-- /.col -->
      </div>
      <?php echo $this->form()->closeTag($form); ?>
    <!-- </form> -->

    <!-- <div class="social-auth-links text-center">
      <p>- OR -</p>
      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
        Facebook</a>
      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
        Google+</a>
    </div> -->
    <!-- /.social-auth-links -->

<!--     <a href="#">I forgot my password</a><br>
    <a href="register.html" class="text-center">Register a new membership</a> -->

  </div>
  <!-- /.login-box-body -->
</div>